export enum DonationActionTypes {
  DONATIONS_REQUESTED = 'DONATIONS_REQUESTED',
  DONATIONS_SUCCESSFUL = 'DONATIONS_SUCCESSFUL',
  DONATIONS_FAILED = 'DONATIONS_FAILED',
}

export enum ParticipantActionTypes {
  PARTICIPANT_REQUESTED = 'PARTICIPANT_REQUESTED',
  PARTICIPANT_SUCCESSFUL = 'PARTICIPANT_SUCCESSFUL',
  PARTICIPANT_FAILED = 'PARTICIPANT_FAILED',
}
